language: julia
os:
  - linux
  - osx
julia:
  - 0.6.3

notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
<<<<<<< HEAD
  # - julia -e 'Pkg.clone(pwd()); Pkg.build("QI"); Pkg.test("QI"; coverage=true)'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("QI")'
=======
  - julia -e 'Pkg.clone(pwd()); Pkg.build("QI"); Pkg.add("StatsBase"); Pkg.test("QI"; coverage=true)'
>>>>>>> master
after_success:
  - julia -e 'cd(Pkg.dir("QI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("QI")); ENV["DOCUMENTER_KEY"] = "true"; include(joinpath("docs", "make.jl"))'
